// Code generated by cqrs-listener. DO NOT EDIT.
package todo

import "github.com/netbrain/splitscreen/cqrs"

const TodoListViewType cqrs.ViewType = "TodoListView"

func init() {

	cqrs.RegisterEventListener(func(event cqrs.Event) {
		cqrs.View(TodoListViewType).(*TodoListView).OnTodoItemCreatedEvent(event.Impl.(*TodoItemCreatedEvent))
	}, TodoItemCreatedEventType)

	cqrs.RegisterEventListener(func(event cqrs.Event) {
		cqrs.View(TodoListViewType).(*TodoListView).OnTodoItemArchivedEvent(event.Impl.(*TodoItemArchivedEvent))
	}, TodoItemArchivedEventType)

	cqrs.RegisterEventListener(func(event cqrs.Event) {
		cqrs.View(TodoListViewType).(*TodoListView).OnTodoItemDeletedEvent(event.Impl.(*TodoItemDeletedEvent))
	}, TodoItemDeletedEventType)

}
